### ISSUE TITLE
Allow controllers to send multiple precursors

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#106]
It seems that in IAPI when sending a custom scan, we can specify multiple precursors and isolation windows, however our codes don't allow this at the moment. 

![image](https://user-images.githubusercontent.com/2523391/91582347-99c51000-e947-11ea-830d-9c25a46d578c.png)

![image](https://user-images.githubusercontent.com/2523391/91582378-a5183b80-e947-11ea-8f6b-576f2f975a37.png)

![image](https://user-images.githubusercontent.com/2523391/91582410-b06b6700-e947-11ea-9fe6-f4e1a321a7c5.png)

**Comment by sdrogers** [comment]
Given that python is so wonderfully not type checked...we should be able to just add lists here:
https://github.com/sdrogers/vimms/blob/bc128a805f8ef1ae934896c5ddedb454d8721e91/vimms/Environment.py#L225-L228
And then have some code in the MS class that checks if the values in those entries are values or lists?

Will require a change here too to cope with a list:
https://github.com/sdrogers/vimms/blob/bc128a805f8ef1ae934896c5ddedb454d8721e91/vimms/MassSpec.py#L141-L152

Propose within the MS (i.e. lower done that method). I.e. controllers pass things as lists of precursors and widths. Within the MS _simulator_, we convert to windows (as we are doing now). I think this method is the only place where we should ever be using windows instead of (mz,width)

I'm not sure what changes will be required to work with the real MS. But I'm sure @joewandy will.

**Comment by sdrogers** [comment]
Also, this will need to change:
https://github.com/sdrogers/vimms/blob/bc128a805f8ef1ae934896c5ddedb454d8721e91/vimms/MassSpec.py#L525-L528
To:
```
else:
  isolation_windows = params.compute_isolation_windows()
```
i.e. no need for `if`, because `ScanParameters.ISOLATION_WINDOWS`  will never have anything in it (or, at least, shouldn't)
