### ISSUE TITLE
test_multiple_chems sometimes fail

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#184]
likely due to randomness

```
___________________ TestDatabaseCreation.test_multiple_chems ___________________

self = <tests.test_chemical_generation.TestDatabaseCreation object at 0x7f16bb190510>

    def test_multiple_chems(self):
        hf = DatabaseFormulaSampler(HMDB, min_mz=MZ_RANGE[0][0], max_mz=MZ_RANGE[0][1])
        ri = UniformRTAndIntensitySampler(min_rt=RT_RANGE[0][0], max_rt=RT_RANGE[0][1])
        cc = ChemicalMixtureCreator(hf, rt_and_intensity_sampler=ri)
        d = cc.sample(N_CHEMS, 2)
    
        group_list = ['control', 'control', 'case', 'case']
        group_dict = {'case': {'missing_probability': 0,
                               'changing_probability': 0}}
    
        # missing noise
        peak_noise = NoPeakNoise()
    
        mm = MultipleMixtureCreator(d, group_list, group_dict, intensity_noise=peak_noise)
    
        cl = mm.generate_chemical_lists()
    
        for c in cl:
            check_chems(c)
            # with these settings all chemicals should be in all lists with identical intensities
            originals = [f.original_chemical for f in c]
>           assert len(set(originals)) == len(d)
E           AssertionError: assert 9 == 10

```

**Comment by sdrogers** [comment]
Ahh, solved it I think. Well, at least _understood_.
The issue is that it is checking that all of the original chemicals are in all of the the individual outputs. i.e.
```
originals = [f.original_chemical for f in c]
assert len(set(originals)) == len(d)
# d is the original list
```
But both `KnownChemical` and `UnknownChemical` have `__eq__` and `__hash__` methods. `UnknownChemical` uses its `key` (which includes rt), `KnownChemical` uses the *chemical formula*

In this example, it looks like HMDB has sampled the same formula twice so that the two objects clash when made into a set.

Possible fixes...can either:
1. Add something to HMDB to (optionally) not pick the same formula more than once. Should only use this for testing -- getting the same formula more than once is good for real experiments.
2. Change the `__eq__` method for `KnownChemical` to include something other than formula. E.g. rt. *But* don't know if this would break anything? @joewandy? @vinnydavies? If we were to change it, we could just add the rt to the formula string?
3. Just check the lengths of the list in the test?

I think probably number 2 is preferable as long as it doesn't break anything further down?

**Comment by sdrogers** [comment]
@joewandy any thoughts on this `__eq__` and `__hash__` methods?

**Comment by joewandy** [comment]
I was the one who added the `__eq__` and `__hash__` to both classes. 

In `UnknownChemical` it was used for evaluation in the first paper -- to determine if the same unknown chemical object were fragmented, or something like that. 

Can't quite remember why those methods were added to `KnownChemical`, probably not used. It should be safe to do option (2) to add the RT to the formula string.
