### ISSUE TITLE
pymzm dependencies

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#7]
Convert pymzm (https://github.com/sdrogers/pymzm) into a proper package so it can be easily added as a dependency in Pipfile.

**Comment by sdrogers** [comment]
Shouldn't this be an issue on the pymzm repo? :-)

**Comment by joewandy** [comment]
yes, can i also be added as a collaborator there please? thanks.

**Comment by joewandy** [comment]
yes, but easier to track if it's all here

**Comment by sdrogers** [comment]
Hi @joewandy -- I started on this, using the mass-spec-utils repo https://github.com/sdrogers/mass-spec-utils
all the code that I think we use in vimms is in there.
Packaged it up, and add to pypi: https://pypi.org/project/mass-spec-utils/0.0.1/
If I make a fresh venv and install this package it is all happy, but then I don't seem to be able to import it? Can you help please?

**Comment by sdrogers** [comment]
From Joe on slack...

Found two things @simon
The folder structure is not correct. Need to move them into a top level  mass_spec_utils  or any other name you prefer
In setup.py we need to specify the dependencies that this package requires. Add a install_requires section in setup.py
(edited)





11:20
image.png 
image.png


11:20
first line shows the incorrect import. Second line fails because requests

**Comment by sdrogers** [comment]
create a folder called mass_spec_utils , add an _init__.py inside it.
Then move adduct_calculator, data_import and library_matching into mass_spec_utils

**Comment by sdrogers** [comment]
Done. See `mass_spec_utils`
