### ISSUE TITLE
Remove code duplications between Roi and SmartRoi Controllers

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#8]
Change these controllers to be one controller -- instead of currently, one extends from the other. It's overly complicated and not necessary.

**Comment by sdrogers** [comment]
Would that mean ROI controller would no longer exist? If so, -1 from me.
If not, then perhaps wait until after experiments? Risks introducing more bugs into code that works.

**Comment by joewandy** [comment]
yeah will do in another branch for sure. But do we still need the old ROI controller (in the superclass)? Seeing that 'smart' is basically the ROI controller

**Comment by sdrogers** [comment]
I think it makes sense to keep it. Maybe we will extend it again with some other ROI class?

**Comment by vinnydavies** [comment]
The reason for doing this is that the SmartRoiController code is basically a duplication of the ROI code, but using SmartRoi instead of Roi. With a small adjustment to SmartRoi so that it works for a more generally we should be able to get rid of a lot of the duplication in the controllers. Both methods will still exist, its just that SmartRoiController will be able to inherit all the currently duplicated code from RoiController

**Comment by joewandy** [comment]
Ok so both classes should stay, and but we reduce the duplicated codes. Changed the title to describe this.
